# General
title: Mario on things
description: Mario's thoughts about random things
baseurl: ""
url: "https://mariopavlovic.github.io/"


# Meta
markdown: kramdown
plugins:
  - jekyll-include-cache


# Minimal Mistakes settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dark"