# General
title: Mario on things
description: Mario's thoughts about random things
baseurl: ""
url: "https://mariopavlovic.github.io/"


# Style
markdown: kramdown
plugins:
- jekyll-remote-theme
remote_theme: pages-themes/slate@v0.2.0