title: Mario on things
description: Mario's thoughts about random things
baseurl: ""
url: "https://mariopavlovic.github.io/"
theme: minimal-mistakes-jekyll

nav:
  - title: "Home"
    url: "/"
  - title: "Mentorship"
    url: "/mentorship/"
